branch-defaults:
  again:
    environment: null
    group_suffix: null
  ebs:
    environment: null
    group_suffix: null
  exp:
    environment: ebs-test-dev
    group_suffix: null
global:
  application_name: ebs-test
  branch: blue
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: blue
  sc: git
  workspace_type: Application
